### PR TITLE
Bump up device  api verison

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

### CODE REVIEW

**Review by kevin-wangzefeng — COMMENTED** [review]
/lgtm
/approve

**Comment by zhangweidongyyl** [comment]
> Signed-off-by: Xiang Dai [long0dai@foxmail.com](mailto:long0dai@foxmail.com)

do you test it?  when i use this in kubeedge-1.4.0,kubeedge-counter-demo can not work ,  just update crd.yaml can not resolve question

**Comment by daixiang0** [comment]
It is the first step :)

**Comment by kevin-wangzefeng** [comment]
Manually merging as bot not yet enabled on this repo

**Pull request merged**
